### ISSUE TITLE
WriteDataAsync does not work in Firefox

### ISSUE THREAD

**Issue by fabudakt** [p6laris/ClipLazor#3]
If I try to write data into the clipboard in Firefox, I get the following error message:

`Error copying data to clipboard: ReferenceError: ClipboardItem is not defined`

I'm not sure if it would be possible to fix this as Firefox is not fully supporting clipboard features but maybe there is a fix for this.

**Comment by p6laris** [comment]
Hi 

Yes you're right, it partially supports the api as it only supports **clipboard-write**, **writeText** [here](https://caniuse.com/?search=Asynchronous%20Clipboard%20API). 

I wonder if we can use the **execCommand** to write and read text and files if the clipboard api is not supported, since the most browsers support the **execCommand**.
